#line 2 "/home/borti/Tesi/minerule/debug/Parsers/MineruleParser_lexer.cpp"

#line 4 "/home/borti/Tesi/minerule/debug/Parsers/MineruleParser_lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer mr_create_buffer
#define yy_delete_buffer mr_delete_buffer
#define yy_flex_debug mr_flex_debug
#define yy_init_buffer mr_init_buffer
#define yy_flush_buffer mr_flush_buffer
#define yy_load_buffer_state mr_load_buffer_state
#define yy_switch_to_buffer mr_switch_to_buffer
#define yyin mrin
#define yyleng mrleng
#define yylex mrlex
#define yylineno mrlineno
#define yyout mrout
#define yyrestart mrrestart
#define yytext mrtext
#define yywrap mrwrap
#define yyalloc mralloc
#define yyrealloc mrrealloc
#define yyfree mrfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE mrrestart(mrin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int mrleng;

extern FILE *mrin, *mrout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up mrtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up mrtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via mrrestart()), so that the user can continue scanning by
	 * just pointing mrin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when mrtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int mrleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow mrwrap()'s to do buffer switches
 * instead of setting up a fresh mrin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void mrrestart (FILE *input_file  );
void mr_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE mr_create_buffer (FILE *file,int size  );
void mr_delete_buffer (YY_BUFFER_STATE b  );
void mr_flush_buffer (YY_BUFFER_STATE b  );
void mrpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void mrpop_buffer_state (void );

static void mrensure_buffer_stack (void );
static void mr_load_buffer_state (void );
static void mr_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER mr_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE mr_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE mr_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE mr_scan_bytes (yyconst char *bytes,int len  );

void *mralloc (yy_size_t  );
void *mrrealloc (void *,yy_size_t  );
void mrfree (void *  );

#define yy_new_buffer mr_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        mrensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            mr_create_buffer(mrin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        mrensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            mr_create_buffer(mrin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *mrin = (FILE *) 0, *mrout = (FILE *) 0;

typedef int yy_state_type;

extern int mrlineno;

int mrlineno = 1;

extern char *mrtext;
#define yytext_ptr mrtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up mrtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	mrleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[198] =
    {   0,
        0,    0,   19,   18,   17,    1,    2,   18,   18,    9,
        7,    7,    3,    3,    3,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   10,    1,    0,   15,    0,    7,    8,    0,
        0,    7,    3,   14,   14,    6,   14,   14,   14,    6,
       14,   14,    0,   14,   14,   14,   14,   14,   14,   14,
       14,   14,    6,   14,   14,   14,   14,   14,    6,   14,
       14,   14,   14,   14,   14,   16,    0,   16,    6,   13,
       14,   14,   14,   14,   14,    0,   14,    0,   14,    6,
       14,   14,    6,   14,   14,   14,   14,   14,   13,    6,

       13,    6,   14,   14,   14,   14,   14,   13,   13,   14,
       14,   14,   14,   14,    6,   14,   14,    0,    0,   14,
        0,   14,   14,    6,   14,   14,    6,   14,    6,    6,
       14,    6,   14,   14,   14,   14,   14,    6,    6,   14,
        0,   14,   14,    0,   14,    0,   14,    6,   14,    0,
       14,    6,    6,   14,   14,    6,   14,    6,   14,   11,
       14,   14,    0,   14,    0,   14,    6,   12,   14,    6,
       14,   14,    6,   11,    6,   14,    0,   14,    0,   14,
       12,    6,   14,    6,   14,    4,    6,    5,   14,    6,
        6,   14,   14,    6,    6,    6,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    5,    4,
        4,    1,    1,    4,    6,    7,    8,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,   12,
       13,   14,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   24,
       40,    1,   41,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   24,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   24,    1,   67,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1
    } ;

static yyconst flex_int16_t yy_base[204] =
    {   0,
        0,    0,  398,  422,  422,  391,  422,  386,   59,  382,
       63,   67,   65,  422,  375,   52,   52,   63,   75,   62,
       43,   79,   82,  103,    0,   72,   81,   64,   74,   74,
      109,  117,  422,  384,  363,  422,  138,  142,  422,  132,
      144,  153,  422,    0,  128,    0,  134,  145,  141,    0,
      130,  141,  155,  142,  170,  158,  146,  155,  156,  161,
      155,  167,    0,  174,  170,  159,  180,  169,  181,  186,
      188,  210,  204,  196,  189,  223,  227,  235,    0,    0,
      206,  201,  201,  209,  227,  240,  215,  241,  282,    0,
      219,  227,    0,  220,  237,  244,  237,  247,    0,    0,

      249,    0,  251,  252,  253,  239,  245,    0,    0,  249,
      248,  261,  257,  270,  277,  258,  270,  277,  265,  274,
      217,  291,  288,    0,  275,  280,  170,  280,    0,    0,
      282,  282,  293,  297,  284,  291,  303,    0,    0,  305,
        0,  307,  309,   89,  301,  325,  313,    0,  312,    0,
      315,    0,    0,  305,  318,    0,  316,    0,  321,    0,
      319,  334,   67,  340,  349,  325,    0,    0,  329,    0,
      347,  335,    0,    0,    0,  342,   59,  338,   57,  342,
        0,  341,  358,    0,  362,  422,    0,  422,  354,    0,
      350,  361,  363,    0,    0,    0,  422,  412,  414,   84,

       81,  416,  418
    } ;

static yyconst flex_int16_t yy_def[204] =
    {   0,
      197,    1,  197,  197,  197,  197,  197,  198,  197,  197,
      197,  197,  197,  197,  197,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  197,  197,  198,  197,  197,  197,  197,  197,
      197,  197,  197,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  197,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  197,  197,  197,  199,  199,
      199,  199,  199,  199,  199,  197,  199,  197,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  197,  197,  199,
      197,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      200,  199,  199,  197,  199,  197,  199,  199,  199,  201,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  202,
      199,  199,  197,  199,  197,  199,  199,  203,  199,  199,
      199,  199,  199,  202,  199,  199,  197,  199,  197,  199,
      203,  199,  199,  199,  199,  197,  199,  197,  199,  199,
      199,  199,  199,  199,  199,  199,    0,  197,  197,  197,

      197,  197,  197
    } ;

static yyconst flex_int16_t yy_nxt[490] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,   12,
        7,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,   27,   28,   29,   25,
       25,   30,   31,   25,   25,   25,   32,   25,   25,   33,
       33,    4,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   25,   25,   30,   31,
       25,   25,   25,   32,   25,   25,    4,   37,   38,   40,
       48,   37,   37,   40,   58,   42,   42,   43,   43,   45,
       49,   41,   53,  168,   46,   41,  160,   47,   51,   56,
       50,   52,   68,   59,   65,   66,   61,   54,   48,   57,

       62,   58,  188,   67,  186,   69,   45,   49,   70,   41,
       60,   46,  177,   41,   47,   51,   56,   50,   52,   68,
       55,   59,   65,   66,   61,   54,   57,   71,   62,   41,
       63,   67,   69,   41,  163,   70,   64,   60,   74,   75,
       76,   76,   72,   73,   40,   79,   37,   37,   40,   77,
       42,   42,   78,   78,   80,   71,   41,   63,   83,   40,
       41,   42,   42,   64,   84,   81,   74,   75,   85,   72,
       73,   41,   86,   79,   87,   90,  150,   53,   82,   91,
       88,   96,   80,   92,   41,   93,   83,   89,   41,   94,
       95,   84,   97,   81,   98,   85,   99,  100,  103,   41,

       86,   87,  102,   90,   41,   82,   91,  101,   41,   96,
       92,  104,   93,  105,  111,   89,   94,   95,  106,   41,
       97,   98,  112,   99,  107,  100,  103,  108,  113,  102,
      109,   76,   76,  110,  101,   78,   78,  114,  104,  115,
      105,  116,  111,   78,   78,  106,  117,  118,  120,  112,
      123,   88,  107,  124,  125,  108,  113,  109,  121,  126,
      110,  127,  146,  128,  114,  129,  115,  130,  116,  131,
      132,  133,  118,  134,  117,  120,  135,  123,  136,  137,
      124,  125,  138,  141,  139,  119,  121,  126,  140,  127,
      128,  142,  143,  129,  144,  130,  145,  131,  132,  133,

      134,   88,  147,  135,  148,  136,  137,  149,   89,  154,
      138,  139,  151,  152,  153,  155,  140,  156,  142,  157,
      143,  158,  144,  159,  145,  161,  162,  122,  164,  166,
      147,  148,  167,  169,  149,  165,   89,  154,  170,  151,
      152,  153,  121,  155,  156,  171,  157,  172,  173,  158,
      175,  159,  176,  161,  162,  164,  178,  166,  180,  165,
      167,  169,  182,  183,  189,  170,  179,   36,  184,  185,
      121,  187,  171,  190,  172,  173,  191,  175,  192,  195,
      176,  193,  194,  196,  178,  180,   34,   43,   39,  182,
       36,  183,  189,   34,  179,  184,  185,  197,  187,  197,

      190,  197,  197,  197,  191,  197,  192,  195,  193,  194,
      197,  196,   35,   35,   35,   44,   44,  174,  174,  181,
      181,    3,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197
    } ;

static yyconst flex_int16_t yy_chk[490] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,    9,   11,
       17,   11,   11,   12,   21,   12,   12,   13,   13,   16,
       17,   11,   19,  201,   16,   12,  200,   16,   18,   20,
       17,   18,   28,   22,   26,   27,   23,   19,   17,   20,

       23,   21,  179,   27,  177,   29,   16,   17,   30,   11,
       22,   16,  163,   12,   16,   18,   20,   17,   18,   28,
       19,   22,   26,   27,   23,   19,   20,   31,   23,   11,
       24,   27,   29,   12,  144,   30,   24,   22,   32,   32,
       40,   40,   31,   31,   37,   45,   37,   37,   38,   41,
       38,   38,   41,   41,   47,   31,   37,   24,   49,   42,
       38,   42,   42,   24,   51,   48,   32,   32,   52,   31,
       31,   42,   53,   45,   54,   56,  127,   55,   48,   57,
       55,   62,   47,   58,   37,   59,   49,   55,   38,   60,
       61,   51,   64,   48,   65,   52,   66,   67,   69,   42,

       53,   54,   68,   56,   37,   48,   57,   67,   38,   62,
       58,   70,   59,   71,   74,   55,   60,   61,   71,   42,
       64,   65,   75,   66,   72,   67,   69,   72,   81,   68,
       73,   76,   76,   73,   67,   77,   77,   82,   70,   83,
       71,   84,   74,   78,   78,   71,   85,   86,   87,   75,
       91,   88,   72,   92,   94,   72,   81,   73,   88,   95,
       73,   96,  121,   97,   82,   98,   83,  101,   84,  103,
      104,  105,  119,  106,   85,   87,  107,   91,  110,  111,
       92,   94,  112,  115,  113,   86,   88,   95,  114,   96,
       97,  116,  117,   98,  118,  101,  120,  103,  104,  105,

      106,  122,  123,  107,  125,  110,  111,  126,  122,  133,
      112,  113,  128,  131,  132,  134,  114,  135,  116,  136,
      117,  137,  118,  140,  120,  142,  143,   89,  145,  147,
      123,  125,  149,  151,  126,  146,  122,  133,  154,  128,
      131,  132,  146,  134,  135,  155,  136,  157,  159,  137,
      161,  140,  162,  142,  143,  145,  164,  147,  166,  165,
      149,  151,  169,  171,  180,  154,  165,   35,  172,  176,
      146,  178,  155,  182,  157,  159,  183,  161,  185,  192,
      162,  189,  191,  193,  164,  166,   34,   15,   10,  169,
        8,  171,  180,    6,  165,  172,  176,    3,  178,    0,

      182,    0,    0,    0,  183,    0,  185,  192,  189,  191,
        0,  193,  198,  198,  198,  199,  199,  202,  202,  203,
      203,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int mr_flex_debug;
int mr_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *mrtext;
#line 1 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
#line 2 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"

#include "minerule/Parsers/ParsedPredicate.hpp"
#include "minerule/Parsers/HeaderQuery.hpp"
#include "minerule/Parsers/SupportMeasure.hpp"
#include "MineruleParser_parser.hpp"
#include <string.h>
#include "minerule/Utils/Converter.hpp"
#include <sstream>
#include <map>
#include <iostream>

using namespace minerule;


int mrlex();

#define PARSER_BUF_SIZE (1<<14)

char linebuf[PARSER_BUF_SIZE];
int tokenpos=0;
int lastC=0;
char* stringUpperCase(char*);
std::map<std::string,int> keywords_to_token;

void append_to_linebuf(char* str);
#define YY_NO_INPUT 1
#line 680 "/home/borti/Tesi/minerule/debug/Parsers/MineruleParser_lexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int mrlex_destroy (void );

int mrget_debug (void );

void mrset_debug (int debug_flag  );

YY_EXTRA_TYPE mrget_extra (void );

void mrset_extra (YY_EXTRA_TYPE user_defined  );

FILE *mrget_in (void );

void mrset_in  (FILE * in_str  );

FILE *mrget_out (void );

void mrset_out  (FILE * out_str  );

int mrget_leng (void );

char *mrget_text (void );

int mrget_lineno (void );

void mrset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int mrwrap (void );
#else
extern int mrwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( mrtext, mrleng, 1, mrout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( mrin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( mrin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, mrin))==0 && ferror(mrin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(mrin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int mrlex (void);

#define YY_DECL int mrlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after mrtext and mrleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 40 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"


#line 868 "/home/borti/Tesi/minerule/debug/Parsers/MineruleParser_lexer.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! mrin )
			mrin = stdin;

		if ( ! mrout )
			mrout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			mrensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				mr_create_buffer(mrin,YY_BUF_SIZE );
		}

		mr_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of mrtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 198 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 422 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{	tokenpos=tokenpos+mrleng;
					append_to_linebuf(mrtext);
		      }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{ tokenpos=tokenpos+mrleng;
			append_to_linebuf(mrtext);
			return mrtext[0];
		      }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
							tokenpos=tokenpos+mrleng;
							append_to_linebuf(mrtext);
							mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
							return(COMPARISON);
                         }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
              tokenpos=tokenpos+mrleng;

              append_to_linebuf(mrtext);
              mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
              return(DATE_MR);
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
              tokenpos=tokenpos+mrleng;

              append_to_linebuf(mrtext);
              mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
              return(TIME_);
                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
				char* stringUpperCase(char*);
				tokenpos=tokenpos+mrleng;
                                append_to_linebuf(mrtext);
				return keywords_to_token[stringUpperCase(mrtext)];
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
			 		tokenpos=tokenpos+mrleng;
			 		append_to_linebuf(mrtext);
					mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
			 		return(INT_NUMBER);
 			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 86 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
				tokenpos=tokenpos+mrleng;
				append_to_linebuf(mrtext);
				return(DOTS);
			 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
                tokenpos=tokenpos+mrleng;
                append_to_linebuf(mrtext);
                return(SINGLE_DOT);
             }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
                tokenpos=tokenpos+mrleng;
                append_to_linebuf(mrtext);
                return(SQUARE);
             }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
				tokenpos=tokenpos+mrleng;
                                append_to_linebuf(mrtext);
				mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
				return(PARTBODY);
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
				tokenpos=tokenpos+mrleng;
                                append_to_linebuf(mrtext);
				mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
				return(PARTHEAD);
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
                          tokenpos=tokenpos+mrleng;
                          append_to_linebuf(stringUpperCase(mrtext));
                          mrlval.TString=strndup(stringUpperCase(mrtext),PARSER_BUF_SIZE);
                          return(AGGREGATE);
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 124 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
			  tokenpos=tokenpos+mrleng;

			  append_to_linebuf(mrtext);
			  mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
			  return(ATTR);
		        }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 132 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
			 if(!lastC) {
				tokenpos=0;
				linebuf[0]='\0';
			 }
			 tokenpos=tokenpos+mrleng;
			 append_to_linebuf(mrtext);
			 mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
 			 return(QUOTED_VALUE);
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{	tokenpos=tokenpos+mrleng;
							append_to_linebuf(mrtext);
							mrlval.TString=strndup(mrtext,PARSER_BUF_SIZE);
							return(DBL_NUMBER);
			     }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 150 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
{
						if (lastC) {
								tokenpos=tokenpos+mrleng;
								append_to_linebuf(mrtext);
								lastC=0;
								return 0;
						} else {
							 	tokenpos=0;
							 	linebuf[0]='\0';
						}
				}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 162 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"
ECHO;
	YY_BREAK
#line 1131 "/home/borti/Tesi/minerule/debug/Parsers/MineruleParser_lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed mrin at a new source and called
			 * mrlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = mrin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( mrwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * mrtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of mrlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					mrrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			mrrestart(mrin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) mrrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 198 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 198 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 197);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					mrrestart(mrin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( mrwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve mrtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void mrrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        mrensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            mr_create_buffer(mrin,YY_BUF_SIZE );
	}

	mr_init_buffer(YY_CURRENT_BUFFER,input_file );
	mr_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void mr_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		mrpop_buffer_state();
	 *		mrpush_buffer_state(new_buffer);
     */
	mrensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	mr_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (mrwrap()) processing, but the only time this flag
	 * is looked at is after mrwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void mr_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	mrin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE mr_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) mralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mr_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) mralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in mr_create_buffer()" );

	b->yy_is_our_buffer = 1;

	mr_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with mr_create_buffer()
 * 
 */
    void mr_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		mrfree((void *) b->yy_ch_buf  );

	mrfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a mrrestart() or at EOF.
 */
    static void mr_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	mr_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then mr_init_buffer was _probably_
     * called from mrrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void mr_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		mr_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void mrpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	mrensure_buffer_stack();

	/* This block is copied from mr_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from mr_switch_to_buffer. */
	mr_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void mrpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	mr_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		mr_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void mrensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)mralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in mrensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)mrrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in mrensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE mr_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) mralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mr_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	mr_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to mrlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       mr_scan_bytes() instead.
 */
YY_BUFFER_STATE mr_scan_string (yyconst char * yystr )
{
    
	return mr_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to mrlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE mr_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) mralloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in mr_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = mr_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in mr_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up mrtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		mrtext[mrleng] = (yy_hold_char); \
		(yy_c_buf_p) = mrtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		mrleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int mrget_lineno  (void)
{
        
    return mrlineno;
}

/** Get the input stream.
 * 
 */
FILE *mrget_in  (void)
{
        return mrin;
}

/** Get the output stream.
 * 
 */
FILE *mrget_out  (void)
{
        return mrout;
}

/** Get the length of the current token.
 * 
 */
int mrget_leng  (void)
{
        return mrleng;
}

/** Get the current token.
 * 
 */

char *mrget_text  (void)
{
        return mrtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void mrset_lineno (int  line_number )
{
    
    mrlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see mr_switch_to_buffer
 */
void mrset_in (FILE *  in_str )
{
        mrin = in_str ;
}

void mrset_out (FILE *  out_str )
{
        mrout = out_str ;
}

int mrget_debug  (void)
{
        return mr_flex_debug;
}

void mrset_debug (int  bdebug )
{
        mr_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from mrlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    mrin = stdin;
    mrout = stdout;
#else
    mrin = (FILE *) 0;
    mrout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * mrlex_init()
     */
    return 0;
}

/* mrlex_destroy is for both reentrant and non-reentrant scanners. */
int mrlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		mr_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		mrpop_buffer_state();
	}

	/* Destroy the stack itself. */
	mrfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * mrlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *mralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *mrrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void mrfree (void * ptr )
{
	free( (char *) ptr );	/* see mrrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 162 "/home/borti/Tesi/minerule/src/Parsers/MineruleParser.lpp"



void append_to_linebuf(char* str) {
	int curlen = strlen(linebuf);
	int charsLeft = PARSER_BUF_SIZE - curlen - 1;
	if( charsLeft < 0) {
		std::cout << "Buffer overflow!" << std::endl;
	}

	if( charsLeft == 0 ) {
		std::cout << "append_to_linebuf: No more space on the buffer..., skipping buffer append!";
	} else {
/*		std::cout << "appending " << strlen(str) << " chars to buffer (chars left:" << charsLeft << " )" << std::endl;*/
		strncat(linebuf, str, charsLeft);
	}
}

void mrerror(char const *s){
	char buf[4096];
	std::stringstream ss;
	ss << s << " at column: " << tokenpos << std::endl << linebuf << std::endl;
	for(int i=0; i<tokenpos+1; ++i)
	   buf[i]=' ';
	buf[tokenpos+1]='\0';
	ss << buf << "^" << std::endl;
	throw MineruleException(MR_ERROR_MINERULETEXT_PARSING, ss.str() );
}

int mrwrap() {
	return 1;
}

//This function converts from very small to capital one world
//received from the lexer
char*
stringUpperCase(char* mrtext) {
  int len=strlen(mrtext);
  for(int i=0;i<len;++i) {
    mrtext[i]=toupper(mrtext[i]);
  }
  return mrtext;
}

