SRCDIR = .
#OBJS =  StringTokenizer.o go.o go2.o go3.o utils.o sqlCoreConn.o core.o  ../../../bobo/sourcerow*.o options.o 

OBJS =  go3.o sqlCoreConn.o core.o  options.o 
LIBS = -L../lib -lsourcerow -lodbc++

#OBJS FOR PARTITION WITHOUT CLUSTERS
OBJS4PWC =  go2.o sqlCoreConn.o partitionWithoutCluster.o options.o 

#INCLUDES = -I. -I.. -I../../../Mrdt/wxstring
INCLUDES = -I. -I..

C++FLAGS = -g $(INCLUDES) -Wall
#C++FLAGS = -O4 $(INCLUDES) -Wno-deprecated

all: core.exe partitionWithoutCluster.exe

core.exe: $(OBJS)
	g++ -o core.exe $(OBJS) $(LIBS)

partitionWithoutCluster.exe:$(OBJS4PWC)
	g++ -o partitionWithoutCluster.exe $(OBJS4PWC) $(LIBS)

go.o: $(SRCDIR)/go.cpp tree.h treenode.h Counter.h sqlCoreConn.h
	g++ $(C++FLAGS) -c $<

go2.o: $(SRCDIR)/go2.cpp itemSet.h itemSetEntry.h itemSetList.h newItemSetHashMap.h sqlCoreConn.h
	g++ $(C++FLAGS) -c $<

$(SRCDIR)/utils.cpp: utils.h
	touch $(SRCDIR)/utils.cpp

$(SRCDIR)/sqlCoreConn.cpp: sqlCoreConn.h
	touch $(SRCDIR)/sqlCoreConn.cpp


go3.o: $(SRCDIR)/go3.cpp itemSetCluster.h itemSetEntryCluster.h gidCidList.h  itemSetListCluster.h sqlCoreConn.h newItemSetHashMap.h
	g++ $(C++FLAGS) -c $<


%.o: $(SRCDIR)/%.cpp
	g++ $(C++FLAGS) -c $<


clean:
	rm -f *.o
	rm -f core.exe
	rm -f partitionWithoutCluster.exe
